server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo
  profiles:
    active: native
  application:
    name: ConfigServer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8500/eureka
